### ISSUE TITLE
ask for advice

### ISSUE THREAD

**Issue by zcdliuwei** [ddowd97/Python-Image-Morpher#4]
Hello, What an interesting show!
I tried with photos of cats and dogs, and the results are as follows：
<img width="1436" alt="result" src="https://user-images.githubusercontent.com/36565076/104142538-03295500-53f7-11eb-9520-09719be5fe1b.png">

It seems that the effect is not ideal. Do you have any suggestions？
Thanks

**Comment by ddowd97** [comment]
Hello, thanks for checking out my project! My current thoughts are that more points are needed for accuracy, but something definitely looks off here. Can you send me the image files that you're using? I'll try to look into why this is happening tomorrow.

**Comment by zcdliuwei** [comment]
> Hello, thanks for checking out my project! My current thoughts are that more points are needed for accuracy, but something definitely looks off here. Can you send me the image files that you're using? I'll try to look into why this is happening tomorrow.

Thank you for your prompt reply，Here are the two source files I used：
![cat](https://user-images.githubusercontent.com/36565076/104143385-286b9280-53fa-11eb-89b9-305eb1e52ef5.png)
![dog](https://user-images.githubusercontent.com/36565076/104143392-2d304680-53fa-11eb-8f1c-72d2c212ffaf.jpg)

**Comment by ddowd97** [comment]
Thanks! Also, on closer inspection, it looks like some of your placed points don't correspond. For example, the two green points are on a hind leg and a tail (some of the triangles on the right look weird for this reason). With this program you want to place points on similar things (i.e. the left eye of each image) which might be hard with these two images.

Give me about a day and I'll follow up on this to be sure.

**Comment by zcdliuwei** [comment]
> Thanks! Also, on closer inspection, it looks like some of your placed points don't correspond. For example, the two green points are on a hind leg and a tail (some of the triangles on the right look weird for this reason). With this program you want to place points on similar things (i.e. the left eye of each image) which might be hard with these two images.
> 
> Give me about a day and I'll follow up on this to be sure.

I understand what you mean. I just chose some points as anchor。
I think the migration between cats and dogs should be relatively simple, at least relative to more complex images, such as a circle to a dog。
The example of wolf and tiger that you showed has good effect, partly because they are very similar animals, and you accurately correspond to the details such as eyes, so you can have a good reference when moving the triangle。

If it is two different kinds of images, such as cat to person, the deformation is much more difficult. Does this limit the application of the code, because it seems that the same kind of images must be used, and the reference point needs to be given more accurately?

**Comment by ddowd97** [comment]
I was curious so I ended up looking at this tonight instead of tomorrow. Here's what I threw together after ~15 minutes.

![image](https://user-images.githubusercontent.com/46535104/104146581-cfb3df80-5390-11eb-999c-0c8b670d740b.png)

The distortion around the tail/head is primarily due to the fact that they are right against the border of the image for the cat. Since these parts are directly touching the edges of that image, PIM by design can't assume that we want white space to be there (hence the black stretching effect). If the cat was centered like the dog is, I imagine this artifacting would be reduced by a lot. As for the artifacts around the feet.. eh, honestly I didn't know how to map a relationship between the two there. Otherwise this is perfectly doable, I think. :)

As for your question about the limitation of application with this project: not exactly. Of course, I will concede that you will typically get the best results when you have two similar images (especially of faces); however, I have actually experimented with animal to human image morphs with great success - so that's definitely possible - but you can even morph more abstract things like 3D shapes if you place your points correctly. My rule of thumb is that when it's too hard to place points by visual correspondence (i.e. left eye to left eye) you should instead place points by physical location (i.e. top left corner of object A to the top left corner of object B).

[Here's a link](https://ufile.io/f/lcvv3) to the two text files PIM generated for my point placements, if you want to use them.

Lastly, here is a 10 frame gif of what I managed! Obviously it could look better, but you get the idea.

<p align="center">
  <img src="https://i.imgur.com/HsROvbH.gif"><br>
</p>

**Comment by zcdliuwei** [comment]
Hello, I still haven't reproduced your results, even if I imitate your point selection, it seems that the order of points has a great influence。

In my opinion, it's very skillful to take some point，
For example, the red points in your example above cover the contours of cats and dogs, and there is a corresponding order between them, but I don't know how to get the blue points。So can you give a general description of how to take points?

Another way of thinking, if I use OpenCV contour detection algorithm, first get the edge points of cats and dogs, and then use corner detection to get some key points with large color value changes inside the object, and then apply your deformation method, will this omit the step of manual point selection, and the code will be more automated? （Of course, we must ensure that the number of points of the two targets is the same）

**Comment by zcdliuwei** [comment]
![res](https://user-images.githubusercontent.com/36565076/104152433-7db79c00-541a-11eb-86bb-f69897fef13e.png)

**Comment by ddowd97** [comment]
Another thread ([here](https://github.com/ddowd97/Python-Image-Morpher/issues/2)) brought up the same idea with contour + color detection - you can see some of his results there too. Admittedly while my project emulates some functionality of OpenCV, I've never actually used the module yet, so I can't personally speak to how well the idea could work in practice. In the future I do intend to either utilize OpenCV's ```goodFeaturesToTrack()``` or construct something similar as an extra feature in PIM (because I do understand why this gets requested occasionally.. placing points can be difficult). At this point in time, though, I'm not confident that automating this process could consistently produce better results than when done manually.

> For example, the red points in your example above cover the contours of cats and dogs, and there is a corresponding order between them, but I don't know how to get the blue points。

Regarding why some points are different in color: 
- Red means the point was saved in a previous session
- Blue means the point was saved in the current session
- Green means the point hasn't been saved yet

I decided to add those blue points to further cement relationships between the contours. For example, I created a pair above the middle of each animal's back because one is at an angle and the other is relatively flat. This information can be just as useful for morphing as the contour points because otherwise PIM may make structural assumptions that you didn't intend for (Show Triangles can highlight when this happens).

> So can you give a general description of how to take points?

When I create corresponding contours between unintuitive images, I try to look for corners, rounded edges, or stopping points. This is hard to explain with words so please forgive me in advance for this terrible visual aid I've constructed for you:

<p align="center">
    <img src="https://user-images.githubusercontent.com/46535104/104215548-89956500-53fe-11eb-9397-fdb491d5834a.png" width=350>&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://user-images.githubusercontent.com/46535104/104215565-91550980-53fe-11eb-9227-b30336d2da7a.png" width=350>
</p> 

_I drew pairs of colored lines on each image to show the general relationship between them. For example, both of the animals have a clearly defined back, so I drew a purple line to show that they're pretty much 1:1 there._

You see where I circled the two corners / rounded edges on the underside of each animal? That's how I try to visualize relationships between images when I'm placing points. The same thing goes for the head of each animal: they both have a dip where the red and blue lines meet (base of the snout for the dog, between the ears for the cat), so I worked off of that to segment the heads into 5 separate "pieces." TL;DR: I look for distinctive "edges" and work off of them to map the entire image(s).

Try to visualize what a morph between your images would look like as well as what would happen as one image slowly transforms into the other. What pieces will move where, and is that what you want? Hopefully this helps. :)

**Comment by zcdliuwei** [comment]
> Another thread ([here](https://github.com/ddowd97/Python-Image-Morpher/issues/2)) brought up the same idea with contour + color detection - you can see some of his results there too. Admittedly while my project emulates some functionality of OpenCV, I've never actually used the module yet, so I can't personally speak to how well the idea could work in practice. In the future I do intend to either utilize OpenCV's `goodFeaturesToTrack()` or construct something similar as an extra feature in PIM (because I do understand why this gets requested occasionally.. placing points can be difficult). At this point in time, though, I'm not confident that automating this process could consistently produce better results than when done manually.
> 
> > For example, the red points in your example above cover the contours of cats and dogs, and there is a corresponding order between them, but I don't know how to get the blue points。
> 
> Regarding why some points are different in color:
> 
> * Red means the point was saved in a previous session
> * Blue means the point was saved in the current session
> * Green means the point hasn't been saved yet
> 
> I decided to add those blue points to further cement relationships between the contours. For example, I created a pair above the middle of each animal's back because one is at an angle and the other is relatively flat. This information can be just as useful for morphing as the contour points because otherwise PIM may make structural assumptions that you didn't intend for (Show Triangles can highlight when this happens).
> 
> > So can you give a general description of how to take points?
> 
> When I create corresponding contours between unintuitive images, I try to look for corners, rounded edges, or stopping points. This is hard to explain with words so please forgive me in advance for this terrible visual aid I've constructed for you:
> 
> <img alt="" width="350" src="https://user-images.githubusercontent.com/46535104/104215548-89956500-53fe-11eb-9397-fdb491d5834a.png">    <img alt="" width="350" src="https://user-images.githubusercontent.com/46535104/104215565-91550980-53fe-11eb-9227-b30336d2da7a.png">
> 
> _I drew pairs of colored lines on each image to show the general relationship between them. For example, both of the animals have a clearly defined back, so I drew a purple line to show that they're pretty much 1:1 there._
> 
> You see where I circled the two corners / rounded edges on the underside of each animal? That's how I try to visualize relationships between images when I'm placing points. The same thing goes for the head of each animal: they both have a dip where the red and blue lines meet (base of the snout for the dog, between the ears for the cat), so I worked off of that to segment the heads into 5 separate "pieces." TL;DR: I look for distinctive "edges" and work off of them to map the entire image(s).
> 
> Try to visualize what a morph between your images would look like as well as what would happen as one image slowly transforms into the other. What pieces will move where, and is that what you want? Hopefully this helps. :)

Thank you for your detailed and timely reply，I have a general idea of how to choose a point。

Another question I want to ask is, it's interesting to slowly transform one image to another, but from the perspective of application, is there any way to make the transformation process produce some beautiful and realistic physical results？

For example, in the transition from cat to horse, the outline of dog appears。

**Comment by ddowd97** [comment]
I'm not sure I'm following what you mean. Can you explain more?

**Comment by ddowd97** [comment]
Discussion has ended and there is no bug to report, so this issue is being closed.
