### ISSUE TITLE
Saving a blend as an image sequence

### ISSUE THREAD

**Issue by NoJustAnother** [ddowd97/Python-Image-Morpher#7]
The .gif exported has (sometimes) compression artifacts. How can a blend created in the Python Image Morpher be exported as an image sequence? 
Converting the .gif to an image sequence does not help as the compression artifacts still remain.
Thank You!

**Comment by ddowd97** [comment]
Hi - Thanks for your interest in this project!

> How can a blend created in the Python Image Morpher be exported as an image sequence?

Currently, the GUI does not support saving full blends as multiple frames (instead of as gifs), but this is a good suggestion... In the next feature update, I'll have some combo box added to choose between these two methods for saving full blends. In the meantime, you can accomplish the same thing by performing and saving single blends at each Alpha interval you need.

> The .gif exported has (sometimes) compression artifacts.

By 'sometimes', do you mean that the artifacting is not 100% reproducible, or that only some frames have the issue?
Can you provide more information, such as the following, so I can debug for any potential issues?

1. Input image and text files (most useful) - You can find the text files in the PIM Images_Points folder
    - Otherwise, can you please provide the format, width, height, and bit depth for each input image file?
2. Is 'Transparency Layer' checked when you see the artifacts?
3. What value for 'Full Blend' is used when you see the artifacts?
4. Were the images resized with PIM at any point?

**Comment by NoJustAnother** [comment]
> In the next feature update, I'll have some combo box added to choose between these two methods for saving full blends

Thank you!

> By 'sometimes', do you mean that the artifacting is not 100% reproducible, or that only some frames have the issue?

Well, this issue is not with the Python Image Morpher but with the .gif file format itself. It usually tends to reduce the amount of colours in the images and this results in 'banding'. This was the same reason why I was suggesting to be able to export as multiple frames so that we can combine the frames into a video/file format other than .gif. 

PS: Thank you for all of this! Very much grateful to you!
