### ISSUE TITLE
PyQT errors

### ISSUE THREAD

**Issue by dberga** [ddowd97/Python-Image-Morpher#8]
You must change **_opencv-python_** for _**opencv-python-headless**_ in `requirements.txt`, as when executing the software it crashes as it uses opencv plugins instead of native PyQT ones.

**Comment by ddowd97** [comment]
Hi - thank you for opening this issue. I'm not sure how I haven't experienced it myself across reinstallations... YMMV, I guess.

After some quick testing, I have updated the repo's ```requirements.txt``` file to include **_opencv-python-headless_** instead of **_opencv-python_** and will include this change in releases going forward - next feature release is coming along.

For future reference of myself and anyone else who finds this page on Google (even I did, accidentally), below are more threads on this that go in more detail:

[OpenCV GitHub](https://github.com/opencv/opencv-python/issues/386)
[Qt Forum](https://forum.qt.io/topic/119109/using-pyqt5-with-opencv-python-cv2-causes-error-could-not-load-qt-platform-plugin-xcb-even-though-it-was-found)
[Stack Overflow](https://stackoverflow.com/questions/30483753/python-app-xcb-plugin-fail)

**Comment by dberga** [comment]
And maybe README.md
